import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Link href={"/page/1"}>페이지 이동</Link>
      <body>{children}</body>
    </html>
  );
}
